export default [
  {
    files: ['**/*.js'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        console: 'readonly',
        process: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        test: 'readonly',
        expect: 'readonly',
        describe: 'readonly',
        it: 'readonly',
        beforeEach: 'readonly',
        afterEach: 'readonly',
        jest: 'readonly',
      },
    },
    rules: {
      // ОТКЛЮЧАЕМ ВСЁ ПОДРЯД
      semi: 'off',
      quotes: 'off',
      'arrow-parens': 'off',
      'operator-linebreak': 'off',
      'no-extra-semi': 'off',
      'comma-dangle': 'off',
      indent: 'off',
      'space-before-function-paren': 'off',
      'eol-last': 'off',
      'no-multiple-empty-lines': 'off',
      'padded-blocks': 'off',
      'quote-props': 'off',
      'no-unused-vars': 'off',
      'no-undef': 'off',
      'no-console': 'off',
    },
    ignores: ['coverage/**', 'node_modules/**'],
  },
];
